"""
Data construction for fimcoder-300m: language-balanced, fresh-only, FIM-formatted
2048-token records.

Three things live here, in the order the pipeline uses them:

1. `iter_repos`  — Arrow-level filtering of stack-v3 parquet. Everything except
   `content` is filtered inside Arrow, so we only pay to materialize file bodies
   that actually survive. This is the difference between a $1 prep and a $10 one.
2. `build_doc`   — turns one repo into one training document in one of four shapes
   (repo-FIM / file-FIM / repo-plain / file-plain).
3. `Packer`      — best-fit-decreasing packing of whole documents into fixed
   2048-token records. A FIM document is NEVER split across records: a prefix in
   one window and its middle in the next teaches the model nothing.

Design notes that matter:

* FIM spans are chosen in CHARACTER space, not token space. Real cursors sit
  mid-token (`def get_us|`). Because our tokenizer is byte-level BPE with
  add_prefix_space=False, tokenizing prefix/middle/suffix separately is lossless,
  so char-level splits cost nothing and buy robustness. (Bavarian et al. 2022.)
* The middle-span distribution imitates an editor: usually the rest of the
  current line, sometimes a block, occasionally a Bavarian-style uniform span.
* Truncation keeps the tokens NEAREST the cursor, which is what minuet sends.
"""

from __future__ import annotations

import json
import os
import random
import re

SEQ = 2048
FRESH = 1_704_067_200          # 2024-01-01 UTC
MIN_BYTES, MAX_BYTES = 120, 100_000

_HERE = os.path.dirname(os.path.abspath(__file__))

# Document shape mixture. file-FIM is the largest single share because it is
# exactly what minuet-ai.nvim sends by default (a bare PSM triple); repo shapes
# teach the model to read neighbouring files when we do give it repo context.
MIX = {"repo_fim": 0.30, "file_fim": 0.40, "repo_plain": 0.15, "file_plain": 0.15}
SPM_FRACTION = 0.25           # share of file_fim emitted suffix-first


def load_lang_mix(path: str | None = None) -> dict[str, float]:
    with open(path or os.path.join(_HERE, "lang_mix.json")) as fh:
        return json.load(fh)


class Specials:
    """Sentinel ids, read from the trained tokenizer so nothing is hard-coded."""

    def __init__(self, tok_dir: str | None = None):
        d = tok_dir or os.path.join(_HERE, "tokenizer")
        with open(os.path.join(d, "specials.json")) as fh:
            m = json.load(fh)
        self.eot = m["<|endoftext|>"]
        self.pre = m["<|fim_prefix|>"]
        self.mid = m["<|fim_middle|>"]
        self.suf = m["<|fim_suffix|>"]
        self.pad = m["<|fim_pad|>"]
        self.repo = m["<|repo_name|>"]
        self.sep = m["<|file_sep|>"]
        self.all = (self.eot, self.pre, self.mid, self.suf, self.pad, self.repo, self.sep)


# ------------------------------------------------------------------ arrow layer

ARROW_COLS = ["repo_path", "github_metadata", "files"]


def lang_array(langs):
    """pc.is_in needs an Arrow value_set, not a Python set."""
    import pyarrow as pa

    return pa.array(sorted(langs), type=pa.string())

_BAD_HEADER = re.compile(
    r"do not edit|do not modify|autogenerated|auto-generated|automatically generated|"
    r"generated by|@generated|code generated by",
    re.I,
)


def arrow_mask(files, langs, pc, ts_min: int = FRESH, ts_max: int = 0):
    """Boolean mask over the FLATTENED files array: in-window, allowed, non-vendor, sane size.

    Runs entirely in Arrow's C++ kernels over the metadata columns. `content` is
    never touched here, which is the whole point. `ts_max` (0 = no bound) lets the
    evaluator pull deliberately STALE code from the same corpus, which is the only
    way to test whether training on fresh-only data actually bought anything.
    """
    flat = pc.list_flatten(files)
    ts = pc.coalesce(flat.field("file_timestamp"), 0)
    ok = pc.and_(
        pc.greater_equal(ts, ts_min),
        pc.is_in(flat.field("language"), value_set=langs),   # langs: pa.Array
    )
    if ts_max:
        ok = pc.and_(ok, pc.less(ts, ts_max))
    ok = pc.and_(ok, pc.equal(pc.coalesce(flat.field("is_vendor"), False), False))
    sz = flat.field("size_bytes")
    ok = pc.and_(ok, pc.greater_equal(sz, MIN_BYTES))
    ok = pc.and_(ok, pc.less_equal(sz, MAX_BYTES))
    return flat, ok


def keep_content(c: str) -> bool:
    """Text-level filters, applied only to files that already survived Arrow.

    stack-v3 has already run StarCoder2's heuristics and MinHash near-dedup
    upstream, so this is deliberately thin: kill minified/generated blobs and
    data-file-shaped things that would waste tokens.
    """
    n = len(c)
    nl = c.count("\n") + 1
    if n / nl > 100:                                    # mean line length
        return False
    if max(map(len, c.split("\n", 4096)), default=0) > 1000:
        return False
    alnum = sum(ch.isalnum() for ch in c[:4000])
    if alnum / min(n, 4000) < 0.25:
        return False
    return not _BAD_HEADER.search(c[:600])


def iter_repos(table, langs, pc, ts_min: int = FRESH, ts_max: int = 0):
    """Yield (repo_path, [file dicts]) for every non-fork repo with surviving files.

    `langs` must be a pyarrow Array (pc.is_in rejects a Python set); build it once
    per worker with `lang_array(...)`.
    """
    md = table.column("github_metadata")
    keep = pc.equal(pc.coalesce(pc.struct_field(md, "is_fork"), False), False)
    table = table.filter(keep)
    if table.num_rows == 0:
        return

    files = table.column("files").combine_chunks()
    flat, ok = arrow_mask(files, langs, pc, ts_min, ts_max)
    parent = pc.list_parent_indices(files)
    idx = pc.indices_nonzero(ok)
    if len(idx) == 0:
        return

    sub = flat.take(idx)
    owners = parent.take(idx).to_pylist()
    paths = table.column("repo_path").to_pylist()
    cols = {
        k: sub.field(k).to_pylist()
        for k in ("content", "content_id", "file_path", "language", "size_bytes")
    }

    cur, bucket = -1, []
    for i, owner in enumerate(owners):
        if owner != cur and bucket:
            yield paths[cur], bucket
            bucket = []
        cur = owner
        c = cols["content"][i]
        if c and keep_content(c):
            bucket.append({
                "content": c,
                "content_id": cols["content_id"][i],
                "path": cols["file_path"][i],
                "lang": cols["language"][i],
                "size": cols["size_bytes"][i],
            })
    if bucket:
        yield paths[cur], bucket


# ------------------------------------------------------------------- FIM spans

def choose_span(text: str, rng: random.Random) -> tuple[str, str, str] | None:
    """Split `text` into (prefix, middle, suffix) at a plausible cursor position.

    Character space on purpose: cursors land mid-token in real editors, and a
    byte-level BPE tokenises the three pieces losslessly, so prefix+middle+suffix
    always reconstructs the file exactly.
    """
    n = len(text)
    if n < 80:
        return None
    lines = text.split("\n")
    if len(lines) < 3:
        cut = sorted(rng.sample(range(1, n), 2))
        return text[: cut[0]], text[cut[0] : cut[1]], text[cut[1] :]

    starts, off = [], 0
    for ln in lines:
        starts.append(off)
        off += len(ln) + 1

    mode = rng.random()
    li = rng.randrange(len(lines) - 1)
    line = lines[li]
    indent = len(line) - len(line.lstrip())

    if mode < 0.50:
        # Rest of the current line: the bread-and-butter editor completion.
        col = rng.randint(indent, max(indent, len(line)))
        a = starts[li] + col
        b = starts[li] + len(line)
    elif mode < 0.80:
        # A block of 2-8 lines starting at the cursor line.
        k = min(rng.randint(2, 8), len(lines) - li)
        col = indent if rng.random() < 0.7 else rng.randint(indent, max(indent, len(line)))
        a = starts[li] + col
        b = starts[min(li + k, len(lines) - 1)] + len(lines[min(li + k, len(lines) - 1)])
    else:
        # Bavarian-style uniform span, keeps the model general.
        a, b = sorted(rng.sample(range(1, n), 2))

    a, b = min(a, n - 1), min(b, n)
    if b <= a:
        b = min(a + 1, n)
    if b - a > 6000:
        b = a + 6000
    return text[:a], text[a:b], text[b:]


def fit_triple(pre, mid, suf, budget, max_mid=512):
    """Trim token lists to `budget` while preserving pre+mid+suf == file.

    Overlong middles spill into the suffix (never truncated away), so the model
    is never asked to emit a middle that does not join its suffix. Prefix keeps
    its tail and suffix keeps its head: the tokens nearest the cursor survive,
    which is exactly the window an editor sends.
    """
    if len(mid) > max_mid:
        suf = mid[max_mid:] + suf
        mid = mid[:max_mid]
    room = budget - len(mid)
    if room < 8:
        return None
    want_p, want_s = (room * 2) // 3, room // 3
    if len(suf) < want_s:
        want_p += want_s - len(suf)
    if len(pre) < want_p:
        want_s += want_p - len(pre)
    return pre[-want_p:], mid, suf[:want_s]


def fim_tokens(pre, mid, suf, sp: Specials, spm: bool = False) -> list[int]:
    if spm:  # suffix-prefix-middle: robustness to how editors assemble prompts
        return [sp.suf, *suf, sp.pre, *pre, sp.mid, *mid, sp.eot]
    return [sp.pre, *pre, sp.suf, *suf, sp.mid, *mid, sp.eot]


def _rank_siblings(target_path: str, files: list[dict], rng: random.Random) -> list[dict]:
    """Order siblings by plausible relevance: same directory first, then same language.

    A real editor's useful context is whatever the target file imports. Same-dir
    and same-language is a cheap proxy that beats a random shuffle.
    """
    tdir = target_path.rsplit("/", 1)[0] if "/" in target_path else ""
    tlang = None
    for f in files:
        if f["path"] == target_path:
            tlang = f["lang"]
            break

    def key(f):
        fdir = f["path"].rsplit("/", 1)[0] if "/" in f["path"] else ""
        same_dir = fdir == tdir
        shared = len(os.path.commonprefix([fdir, tdir]))
        return (
            -(2.0 if same_dir else 0.0)
            - (1.0 if f["lang"] == tlang else 0.0)
            - shared / 200.0
            + rng.random() * 0.9          # jitter so the model never sees a fixed order
        )

    return sorted((f for f in files if f["path"] != target_path), key=key)


# ------------------------------------------------------------- document shapes

def plan_doc(repo_path: str, files: list[dict], rng: random.Random,
             shape: str | None = None, force_lang: str | None = None,
             target: dict | None = None, sib_langs: set | None = None) -> dict | None:
    """Choose a document shape and return its raw text pieces (no tokenizing yet).

    Tokenizing is deferred so a whole parquet batch can go through
    `Tokenizer.encode_batch`, which is Rust-parallel and ~10x faster than
    per-piece calls.
    """
    if not files:
        return None
    if shape is None:
        r, acc = rng.random(), 0.0
        for k, v in MIX.items():
            acc += v
            if r < acc:
                shape = k
                break
        shape = shape or "file_fim"
    if shape.startswith("repo_") and len(files) < 2:
        shape = "file_fim" if shape == "repo_fim" else "file_plain"

    # `target` names the exact file to build the document around; the builder walks
    # every file of an under-quota language rather than sampling one per repo, which
    # is what makes the per-language budgets reachable at all. `force_lang` is the
    # weaker form: pick any file of that language, size-weighted.
    if target is not None:
        tgt = target
    else:
        pool = [f for f in files if f["lang"] == force_lang] if force_lang else files
        if not pool:
            return None
        w = [min(f["size"], 20_000) ** 0.7 for f in pool]
        tgt = rng.choices(pool, weights=w, k=1)[0]

    if shape in ("file_fim", "repo_fim"):
        sp = choose_span(tgt["content"], rng)
        if sp is None:
            shape = "file_plain" if shape == "file_fim" else "repo_plain"
        else:
            pre, mid, suf = sp

    L = tgt["lang"]
    if shape == "file_fim":
        return {"shape": shape, "lang": L, "spm": rng.random() < SPM_FRACTION,
                "pieces": [pre, mid, suf], "plangs": [L, L, L]}
    if shape == "file_plain":
        return {"shape": shape, "lang": L, "plangs": [L],
                "pieces": [tgt["path"] + "\n" + tgt["content"]]}

    # Siblings are restricted to languages still under quota, so repo context does
    # not quietly re-import the languages the budget is trying to hold down.
    pool = files if sib_langs is None else [
        f for f in files if f["lang"] in sib_langs or f["path"] == tgt["path"]
    ]
    sibs = _rank_siblings(tgt["path"], pool, rng)[: rng.randint(1, 6)]
    sib_txt = [f["path"] + "\n" + f["content"] for f in sibs]
    sib_lang = [f["lang"] for f in sibs]
    if shape == "repo_fim":
        return {"shape": shape, "lang": L, "spm": False, "n_sib": len(sib_txt),
                "pieces": [repo_path, *sib_txt, tgt["path"] + "\n", pre, mid, suf],
                "plangs": [L, *sib_lang, L, L, L, L]}
    return {"shape": "repo_plain", "lang": L, "n_sib": len(sib_txt),
            "pieces": [repo_path, *sib_txt, tgt["path"] + "\n" + tgt["content"]],
            "plangs": [L, *sib_lang, L]}


def assemble(plan: dict, enc: list[list[int]], sp: Specials, seq: int = SEQ,
             usage: list[int] | None = None) -> list[int] | None:
    """Turn a plan plus its tokenised pieces into one <= seq-token document.

    If `usage` is given it is filled with the number of tokens actually kept from
    each piece, so the caller can attribute tokens to the right language even in a
    multi-language repo document. Language balance measured at the *document* level
    would over-count whatever happened to be the FIM target; loss is applied to
    every token, so the budget has to be counted the same way.
    """
    shape = plan["shape"]
    u = usage if usage is not None else []
    u.clear()

    if shape == "file_fim":
        t = fit_triple(enc[0], enc[1], enc[2], seq - 4)
        if t is None:
            return None
        u.extend(len(x) for x in t)
        return fim_tokens(*t, sp=sp, spm=plan["spm"])

    if shape == "file_plain":
        keep = enc[0][: seq - 1]
        u.append(len(keep))
        return [*keep, sp.eot]

    head = [sp.repo, *enc[0]]
    n_sib = plan["n_sib"]
    sib_ids: list[int] = []
    u.append(len(enc[0]))

    if shape == "repo_fim":
        # The FIM target keeps the majority of the window; siblings fill what is left.
        avail = seq - len(head) - int(seq * 0.55)
        for i in range(1, 1 + n_sib):
            piece = enc[i]
            if len(sib_ids) + len(piece) + 1 <= avail:
                sib_ids += [sp.sep, *piece]
                u.append(len(piece))
            else:
                room = avail - len(sib_ids) - 1
                if room > 64:                      # a truncated neighbour still informs
                    sib_ids += [sp.sep, *piece[:room]]
                    u.append(room)
                break
        u.extend([0] * (1 + n_sib - len(u)))
        tpath = enc[1 + n_sib]
        budget = seq - len(head) - len(sib_ids) - 1 - len(tpath) - 4
        t = fit_triple(enc[2 + n_sib], enc[3 + n_sib], enc[4 + n_sib], budget)
        if t is None:
            return None
        u.append(len(tpath))
        u.extend(len(x) for x in t)
        return [*head, *sib_ids, sp.sep, *tpath, *fim_tokens(*t, sp=sp)]

    avail = seq - len(head) - 1
    for i in range(1, 1 + n_sib + 1):
        piece = enc[i]
        if len(sib_ids) + len(piece) + 1 <= avail:
            sib_ids += [sp.sep, *piece]
            u.append(len(piece))
        else:
            room = avail - len(sib_ids) - 1
            if room > 64:
                sib_ids += [sp.sep, *piece[:room]]
                u.append(room)
            break
    u.extend([0] * (2 + n_sib - len(u)))
    return [*head, *sib_ids, sp.eot]


# ----------------------------------------------------------------- packing

class Packer:
    """Best-fit-DECREASING packer: whole documents into fixed-length records.

    Documents arrive in read order, which is close to worst case for online
    best-fit: a stream of 1100-token documents pairs with nothing and every record
    ends up ~46% padding (measured: 60.5% fill on the first build). Buffering a few
    thousand documents and packing them largest-first fixes it, because the large
    documents open the bins and the small ones fill them.

    Documents are never split -- a prefix in one record and its middle in the next
    teaches the model nothing. The tail of a record is padded with <|fim_pad|>,
    which appears nowhere else, so the loss mask is just `ids != pad`.
    """

    def __init__(self, sp: Specials, seq: int = SEQ, batch: int = 6000,
                 max_open: int = 4096, min_slack: int = 16):
        self.sp, self.seq = sp, seq
        self.batch, self.max_open, self.min_slack = batch, max_open, min_slack
        self.bins: list[tuple] = []     # (remaining, tie_break, ids) sorted ascending
        self.pending: list[list[int]] = []
        self.ctr = 0
        self.tok_used = 0
        self.tok_pad = 0
        self.n_records = 0

    def _close(self, ids: list[int]) -> list[int]:
        self.tok_used += len(ids)
        self.tok_pad += self.seq - len(ids)
        self.n_records += 1
        return ids + [self.sp.pad] * (self.seq - len(ids))

    def _pack_pending(self):
        import bisect

        self.pending.sort(key=len, reverse=True)
        for doc in self.pending:
            L = len(doc)
            i = bisect.bisect_left(self.bins, (L,))
            if i < len(self.bins):
                rem, c, ids = self.bins.pop(i)
                ids.extend(doc)
                rem -= L
            else:
                rem, ids = self.seq - L, list(doc)
                self.ctr += 1
                c = self.ctr
            if rem < self.min_slack:
                yield self._close(ids)
            else:
                bisect.insort(self.bins, (rem, c, ids))
            while len(self.bins) > self.max_open:
                yield self._close(self.bins.pop()[2])   # emptiest bin, least likely to fill
        self.pending = []

    def add(self, doc: list[int]):
        if 16 <= len(doc) <= self.seq:
            self.pending.append(doc)
        if len(self.pending) >= self.batch:
            yield from self._pack_pending()

    def flush(self):
        yield from self._pack_pending()
        for _rem, _c, ids in self.bins:
            yield self._close(ids)
        self.bins = []

    @property
    def fill(self) -> float:
        t = self.tok_used + self.tok_pad
        return self.tok_used / t if t else 0.0


class LangBudget:
    """Per-language token caps derived from lang_mix.json.

    Quotas CAP but never REQUIRE: a language that runs dry simply ends up short,
    and the shortfall is made up by bounded repetition at pack time rather than
    by stalling the whole job waiting for more Zig.
    """

    def __init__(self, mix: dict[str, float], total_tokens: int, slack: float = 1.15):
        self.mix = mix
        self.cap = {k: int(v * total_tokens * slack) for k, v in mix.items()}
        self.target = {k: int(v * total_tokens) for k, v in mix.items()}
        self.got: dict[str, int] = dict.fromkeys(mix, 0)

    def allow(self, lang: str) -> bool:
        return self.got.get(lang, 1 << 62) < self.cap.get(lang, 0)

    def ratio(self, lang: str) -> float:
        """How full this language is against target; used to pick what to emit next."""
        return self.got.get(lang, 1 << 62) / max(self.target.get(lang, 1), 1)

    def add(self, lang: str, n: int):
        if lang in self.got:
            self.got[lang] += n

    def open_langs(self) -> set[str]:
        return {k for k in self.mix if self.got[k] < self.cap[k]}

    def shortfall(self) -> list[tuple[str, float]]:
        out = [(k, self.got[k] / max(self.target[k], 1)) for k in self.mix]
        return sorted(out, key=lambda x: x[1])

    def report(self, top: int = 24) -> str:
        tot = sum(self.got.values()) or 1
        rows = sorted(self.got.items(), key=lambda x: -x[1])[:top]
        body = "\n".join(
            f"  {k:<22}{v / 1e6:>9.1f}M  {v / tot * 100:>6.2f}%  (target {self.mix[k] * 100:5.2f}%)"
            for k, v in rows
        )
        low = ", ".join(f"{k}:{r * 100:.0f}%" for k, r in self.shortfall()[:12])
        return f"{tot / 1e9:.3f}B tokens over {sum(1 for v in self.got.values() if v)} langs\n{body}\n  short: {low}"
