"""
Train our 32k FIM code tokenizer locally (free) and benchmark it against off-the-shelf
tokenizers on our ACTUAL data distribution (fresh 2024+ filtered code).

Uses gigatoken for training/encoding (~1000x faster than HF tokenizers), then emits a
standard HF tokenizer.json so the trained model stays loadable by vLLM / llama.cpp / minuet.

Usage:
    . .venv/bin/activate
    python train_tokenizer.py sample      # stream + filter a code corpus to /tmp
    python train_tokenizer.py train       # train 32k BPE -> tokenizer/
    python train_tokenizer.py bench       # fertility vs GPT-2 / Qwen-Coder / StarCoder2
"""

import json
import os
import sys
import time

SPECIALS = [
    "<|endoftext|>",
    "<|fim_prefix|>",
    "<|fim_middle|>",
    "<|fim_suffix|>",
    "<|fim_pad|>",
    "<|repo_name|>",
    "<|file_sep|>",
]

VOCAB_SIZE = 32_768
DATASET = "HuggingFaceCode/stack-v3-train"
FRESH = 1_704_067_200  # 2024-01-01 UTC, unix seconds

LANGUAGES = {
    "Python", "TypeScript", "JavaScript", "Go", "Rust", "Java", "C", "C++", "C#",
    "Ruby", "PHP", "Shell", "SQL", "Markdown", "Kotlin", "Dart", "HTML", "CSS",
}

CORPUS = "/tmp/code_sample.txt"       # full filtered sample
TRAIN_SLICE = "/tmp/train_slice.txt"  # first N MB, used to train
HELDOUT = "/tmp/heldout.txt"          # tail, used for fertility comparison
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tokenizer")


# ---------------------------------------------------------------- filters

def keep_file(f) -> bool:
    """Same heuristics as prep_data.py: fresh, real, hand-written source."""
    c = f.get("content")
    if not c or f.get("language") not in LANGUAGES or f.get("is_vendor"):
        return False
    if (f.get("file_timestamp") or 0) < FRESH:
        return False
    n = len(c)
    if n < 120 or n > 100_000:
        return False
    lines = c.split("\n")
    if max((len(x) for x in lines), default=0) > 1000:
        return False
    if n / max(len(lines), 1) > 100:
        return False
    if sum(ch.isalnum() for ch in c) / n < 0.25:
        return False
    low = c[:400].lower()
    return not ("do not edit" in low or "autogenerated" in low or "auto-generated" in low)


def build_sample(target_mb: int = 260, max_parts: int = 8):
    """Stream parquet parts from HF, filter, write one big \\x00-free text file."""
    import pyarrow.parquet as pq
    from huggingface_hub import HfFileSystem

    fs = HfFileSystem()
    parts = [
        p for p in fs.ls(f"datasets/{DATASET}/data", detail=False) if p.endswith(".parquet")
    ]
    budget = target_mb * 1024 * 1024
    seen: set[str] = set()
    total = 0
    t0 = time.time()

    with open(CORPUS, "wb") as out:
        for path in parts[:max_parts]:
            pf = pq.ParquetFile(fs.open(path, "rb"))
            for batch in pf.iter_batches(
                batch_size=200, columns=["github_metadata", "files"]
            ):
                for row in batch.to_pylist():
                    if (row.get("github_metadata") or {}).get("is_fork"):
                        continue
                    for f in row.get("files") or []:
                        if not keep_file(f) or f["content_id"] in seen:
                            continue
                        seen.add(f["content_id"])
                        out.write(f["content"].encode("utf-8", "ignore"))
                        out.write(b"<|endoftext|>")
                        total += len(f["content"])
                if total > budget:
                    break
            if total > budget:
                break

    print(f"sampled {total / 1e6:.0f} MB fresh code in {time.time() - t0:.0f}s -> {CORPUS}")

    # Split: train on the head, measure fertility on unseen tail.
    size = os.path.getsize(CORPUS)
    cut = int(size * 0.62)
    with open(CORPUS, "rb") as fh:
        head = fh.read(cut)
        tail = fh.read()
    # Align splits to document boundaries.
    sep = b"<|endoftext|>"
    head = head[: head.rfind(sep) + len(sep)]
    tail = tail[tail.find(sep) + len(sep):]
    open(TRAIN_SLICE, "wb").write(head)
    open(HELDOUT, "wb").write(tail)
    print(f"train slice {len(head) / 1e6:.0f} MB · heldout {len(tail) / 1e6:.0f} MB")


# ---------------------------------------------------------------- HF export

def _bytes_to_unicode():
    """GPT-2's reversible byte<->unicode map, required by HF ByteLevel BPE."""
    bs = list(range(33, 127)) + list(range(161, 173)) + list(range(174, 256))
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def to_hf_tokenizer(vocab: dict[int, bytes], merges: list[tuple[bytes, bytes]]) -> dict:
    """Convert gigatoken's (id->bytes, merge pairs) into HF tokenizer.json format."""
    b2u = _bytes_to_unicode()

    def enc(bs: bytes) -> str:
        return "".join(b2u[b] for b in bs)

    special_set = {s.encode() for s in SPECIALS}
    hf_vocab: dict[str, int] = {}
    added = []

    for tid, raw in sorted(vocab.items()):
        if raw in special_set:
            tok = raw.decode()
            hf_vocab[tok] = tid
            added.append({
                "id": tid, "content": tok, "single_word": False, "lstrip": False,
                "rstrip": False, "normalized": False, "special": True,
            })
        else:
            hf_vocab[enc(raw)] = tid

    return {
        "version": "1.0",
        "truncation": None,
        "padding": None,
        "added_tokens": added,
        "normalizer": None,
        "pre_tokenizer": {
            "type": "Sequence",
            "pretokenizers": [
                {"type": "Digits", "individual_digits": True},
                {
                    "type": "ByteLevel",
                    "add_prefix_space": False,
                    "trim_offsets": True,
                    "use_regex": True,
                },
            ],
        },
        # null, matching StarCoder2 byte-for-byte. A ByteLevel post-processor only
        # shifts offsets, but keeping the config identical to a tokenizer llama.cpp
        # already recognises removes all doubt at GGUF-conversion time.
        "post_processor": None,
        "decoder": {
            "type": "ByteLevel", "add_prefix_space": True, "trim_offsets": True,
            "use_regex": True,
        },
        "model": {
            "type": "BPE",
            "dropout": None,
            "unk_token": None,
            "continuing_subword_prefix": None,
            "end_of_word_suffix": None,
            "fuse_unk": False,
            "byte_fallback": False,
            "ignore_merges": False,
            "vocab": hf_vocab,
            "merges": [[enc(a), enc(b)] for a, b in merges],
        },
    }


def train():
    import gigatoken as gt

    src = gt.TextFileSource([TRAIN_SLICE], separator=b"<|endoftext|>")
    mb = os.path.getsize(TRAIN_SLICE) / 1e6
    t0 = time.time()
    vocab, merges = gt.train_bpe(src, VOCAB_SIZE, SPECIALS)
    print(f"trained {len(vocab)} BPE on {mb:.0f} MB in {time.time() - t0:.0f}s")

    os.makedirs(OUT_DIR, exist_ok=True)
    spec = to_hf_tokenizer(vocab, merges)
    path = os.path.join(OUT_DIR, "tokenizer.json")
    with open(path, "w") as fh:
        json.dump(spec, fh)

    # Round-trip through HF tokenizers: this is what training/serving will actually use.
    from tokenizers import Tokenizer

    tok = Tokenizer.from_file(path)
    assert tok.get_vocab_size() <= 65535, "vocab must fit uint16"
    for s in SPECIALS:
        assert tok.token_to_id(s) is not None, f"lost special token {s}"

    sample = (
        "<|repo_name|>acme/api<|file_sep|>db.py\n"
        "import os\n\n"
        "<|file_sep|>main.py\n"
        "<|fim_prefix|>def get_user(uid: int):\n    "
        "<|fim_suffix|>\n    return user\n<|fim_middle|>"
        "user = db.query(User).filter_by(id=uid).one()"
    )
    ids = tok.encode(sample).ids
    rt = tok.decode(ids, skip_special_tokens=False)
    print(f"FIM round-trip exact: {rt == sample}")
    print(f"specials -> {[tok.token_to_id(s) for s in SPECIALS]}")

    with open(os.path.join(OUT_DIR, "specials.json"), "w") as fh:
        json.dump({s: tok.token_to_id(s) for s in SPECIALS}, fh, indent=2)
    print(f"wrote {path}")


# ---------------------------------------------------------------- benchmark

def bench():
    """Fertility (chars/token) on HELD-OUT fresh code. Higher = more code per token.

    All candidates go through HF `tokenizers` so the comparison uses one identical code
    path. gigatoken can't reload our custom tokenizer.json (its Sequence pre-tokenizer
    has no Split regex), and 100MB through HF only takes a few seconds.
    """
    from tokenizers import Tokenizer as HFTok

    size = os.path.getsize(HELDOUT)
    with open(HELDOUT, "rb") as fh:
        docs = [d.decode("utf-8", "ignore") for d in fh.read().split(b"<|endoftext|>") if d]
    print(f"held-out: {size / 1e6:.0f} MB / {len(docs):,} unseen fresh (2024+) files\n")
    print(f"{'tokenizer':<34}{'vocab':>8}{'chars/tok':>11}{'embed@1024':>12}")
    print("-" * 65)

    rows = []

    def measure(label, tok, vocab_size):
        n = sum(len(e.ids) for e in tok.encode_batch_fast(docs))
        fert = size / n
        print(f"{label:<34}{vocab_size:>8}{fert:>11.2f}{vocab_size * 1024 / 1e6:>10.1f}M")
        rows.append((label, vocab_size, fert))

    ours_path = os.path.join(OUT_DIR, "tokenizer.json")
    if os.path.exists(ours_path):
        tok = HFTok.from_file(ours_path)
        measure("OURS (32k, code+FIM)", tok, tok.get_vocab_size())

    for repo, label in [
        ("openai-community/gpt2", "GPT-2 (general purpose)"),
        ("bigcode/starcoder2-tokenizer", "StarCoder2 (code, 49k)"),
        ("Qwen/Qwen2.5-Coder-1.5B", "Qwen2.5-Coder (152k)"),
    ]:
        try:
            tok = HFTok.from_pretrained(repo)
            measure(label, tok, tok.get_vocab_size())
        except Exception as e:
            print(f"{label:<34}  skipped: {type(e).__name__}")

    if len(rows) > 1:
        ours = rows[0]
        print("\nrelative to ours:")
        for label, vs, fert in rows[1:]:
            d_tok = (ours[2] / fert - 1) * 100
            d_emb = (vs - ours[1]) * 1024 / 1e6
            print(
                f"  {label:<32} {d_tok:+6.1f}% tokens/char"
                f"   {d_emb:+6.1f}M extra embedding params"
            )


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd in ("sample", "all"):
        build_sample()
    if cmd in ("train", "all"):
        train()
    if cmd in ("bench", "all"):
        bench()
